# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu
  kb_layout = us
  kb_options = compose:caps # ,grp:alts_toggle

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitity for mouse/trackpack (default: 0)
  # sensitivity = 0.35
  

# swap alt and win keys (feels more like a Mac)
kb_options = altwin:swap_alt_win

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }

}

# Scroll faster in the terminal
#windowrule = scrolltouchpad 1.5, match:tag terminal

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/
# gesture = 3, horizontal, workspace

# Logitech g pro - connected wirelessly
device {
  name = logitech-g-pro-1
  sensitivity = -0.9 # takes values in range [-1,1]
  accel_profile = flat
  natural_scroll = no
  scroll_factor = 1.0
}

# Logitech g pro when plugged with wire
device {
  name = logitech-g-pro-wireless-gaming-mouse-2
  sensitivity = -0.9 # takes values in range [-1,1]
  accel_profile = flat
  natural_scroll = no
  scroll_factor = 1.0
}

# T480 trackpoint
device {
  name = tpps/2-ibm-trackpoint
  #sensitivity = 0.25 # takes values in range [-1,1]
  sensitivity = -0.25 # takes values in range [-1,1]
  #accel_profile = flat
  natural_scroll = no
  scroll_factor = 0.8
}

# T480 trackpad
device {
    name = synaptics-tm3276-022
    enabled = false
}
